---
- name: Get repository setup script
  get_url:
    url: https://tarantool-io.hb.bizmrg.com/website-static/tarantool/downloads/tarantool_installer.sh
    dest: '/tmp/tarantool-installer.sh'
  register: get_script
  until: not get_script.failed
  retries: 3
  delay: 5
  any_errors_fatal: true

- name: Run repository setup script
  command: bash /tmp/tarantool-installer.sh --repo-only
  environment:
    VER: '{{ version }}'
  any_errors_fatal: true
  changed_when: false
