---
- name: Manage instance parameters in runtime
  cartridge_instance:
    control_sock: '{{ cartridge_app_name | instance_control_sock(inventory_hostname, stateboard) }}'
    config: '{{ config }}'
    cartridge_defaults: '{{ cartridge_defaults }}'
  when: >-
    not restarted and not expelled and
    (config.memtx_memory is defined or cartridge_defaults.memtx_memory is defined )
  tags: cartridge-instances

- name: Check if instance restart is forced or required to apply changes
  cartridge_needs_restart:
    restart_forced: '{{ restarted }}'
    control_sock: '{{ cartridge_app_name | instance_control_sock(inventory_hostname, stateboard) }}'
    appname: '{{ cartridge_app_name }}'
    instance_conf_file: '{{ cartridge_app_name | instance_conf_file(inventory_hostname, stateboard) }}'
    conf_section_name: '{{ cartridge_app_name | conf_section_name(inventory_hostname, stateboard) }}'
    cluster_cookie: '{{ cartridge_cluster_cookie }}'
    cartridge_defaults: '{{ cartridge_defaults }}'
    config: '{{ config }}'
    stateboard: '{{ stateboard }}'
  notify: restart-instance
  tags: cartridge-instances

- name: Place default config
  copy:
    content: >-
      {{
        { cartridge_app_name: cartridge_defaults | combine({"cluster_cookie": cartridge_cluster_cookie}) }
        | to_nice_yaml
      }}
    dest: '{{ cartridge_app_name | app_conf_file }}'
    owner: tarantool
    group: tarantool
    mode: '644'
  when: not stateboard
  tags: cartridge-instances

- name: Place instance config
  copy:
    content: >-
      {{
        { cartridge_app_name | conf_section_name(inventory_hostname, stateboard): config }
          | to_nice_yaml
      }}
    dest: '{{ cartridge_app_name | instance_conf_file(inventory_hostname, stateboard) }}'
    owner: tarantool
    group: tarantool
    mode: '644'
  tags: cartridge-instances
