---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  listen: reload-systemd-daemon
  tags: cartridge-instances

- name: Restart instance systemd service
  systemd:
    name: '{{ cartridge_app_name | systemd_service_name(inventory_hostname, stateboard) }}'
    state: restarted
    enabled: true
  listen: restart-instance
  tags: cartridge-instances
